//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtasaDesktop.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtasaDesktop.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceder.
        /// </summary>
        public static string Account_Login_Button {
            get {
                return ResourceManager.GetString("Account_Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Account_Login_Title {
            get {
                return ResourceManager.GetString("Account_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string Account_Logout {
            get {
                return ResourceManager.GetString("Account_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Account_User {
            get {
                return ResourceManager.GetString("Account_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de usuario.
        /// </summary>
        public static string Account_UserDetails {
            get {
                return ResourceManager.GetString("Account_UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestor de flotas.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturación.
        /// </summary>
        public static string Billing {
            get {
                return ResourceManager.GetString("Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución.
        /// </summary>
        public static string Distribution {
            get {
                return ResourceManager.GetString("Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rehacer.
        /// </summary>
        public static string Toolbar_Action_Redo {
            get {
                return ResourceManager.GetString("Toolbar_Action_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string Toolbar_Action_Refresh {
            get {
                return ResourceManager.GetString("Toolbar_Action_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Toolbar_Action_Save {
            get {
                return ResourceManager.GetString("Toolbar_Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deshacer.
        /// </summary>
        public static string Toolbar_Action_Undo {
            get {
                return ResourceManager.GetString("Toolbar_Action_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos.
        /// </summary>
        public static string Toolbar_Admin_Groups_Group {
            get {
                return ResourceManager.GetString("Toolbar_Admin_Groups_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos.
        /// </summary>
        public static string Toolbar_Admin_Groups_List {
            get {
                return ResourceManager.GetString("Toolbar_Admin_Groups_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo grupo.
        /// </summary>
        public static string Toolbar_Admin_Groups_New {
            get {
                return ResourceManager.GetString("Toolbar_Admin_Groups_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string Toolbar_Admin_Users_List {
            get {
                return ResourceManager.GetString("Toolbar_Admin_Users_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo usuario.
        /// </summary>
        public static string Toolbar_Admin_Users_New {
            get {
                return ResourceManager.GetString("Toolbar_Admin_Users_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string Toolbar_Clients_Group {
            get {
                return ResourceManager.GetString("Toolbar_Clients_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string Toolbar_Clients_List {
            get {
                return ResourceManager.GetString("Toolbar_Clients_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo cliente.
        /// </summary>
        public static string Toolbar_Clients_New {
            get {
                return ResourceManager.GetString("Toolbar_Clients_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factorias.
        /// </summary>
        public static string Toolbar_Factories_Group {
            get {
                return ResourceManager.GetString("Toolbar_Factories_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factorias.
        /// </summary>
        public static string Toolbar_Factories_List {
            get {
                return ResourceManager.GetString("Toolbar_Factories_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva factoria.
        /// </summary>
        public static string Toolbar_Factories_New {
            get {
                return ResourceManager.GetString("Toolbar_Factories_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignaciones.
        /// </summary>
        public static string Toolbar_Fleet_Assignments {
            get {
                return ResourceManager.GetString("Toolbar_Fleet_Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conductores.
        /// </summary>
        public static string Toolbar_Fleet_Drivers_List {
            get {
                return ResourceManager.GetString("Toolbar_Fleet_Drivers_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo conductor.
        /// </summary>
        public static string Toolbar_Fleet_Drivers_New {
            get {
                return ResourceManager.GetString("Toolbar_Fleet_Drivers_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flota.
        /// </summary>
        public static string Toolbar_Fleet_Group {
            get {
                return ResourceManager.GetString("Toolbar_Fleet_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehículos.
        /// </summary>
        public static string Toolbar_Fleet_Vehicles_List {
            get {
                return ResourceManager.GetString("Toolbar_Fleet_Vehicles_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo vehículo.
        /// </summary>
        public static string Toolbar_Fleet_Vehicles_New {
            get {
                return ResourceManager.GetString("Toolbar_Fleet_Vehicles_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Json.
        /// </summary>
        public static string Toolbar_Json {
            get {
                return ResourceManager.GetString("Toolbar_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operadores.
        /// </summary>
        public static string Toolbar_Operators {
            get {
                return ResourceManager.GetString("Toolbar_Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos.
        /// </summary>
        public static string Toolbar_Orders {
            get {
                return ResourceManager.GetString("Toolbar_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de colores.
        /// </summary>
        public static string Toolbar_Orders_Colors {
            get {
                return ResourceManager.GetString("Toolbar_Orders_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos.
        /// </summary>
        public static string Toolbar_Orders_Group {
            get {
                return ResourceManager.GetString("Toolbar_Orders_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar.
        /// </summary>
        public static string Toolbar_Orders_Import {
            get {
                return ResourceManager.GetString("Toolbar_Orders_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de pedidos.
        /// </summary>
        public static string Toolbar_Orders_List {
            get {
                return ResourceManager.GetString("Toolbar_Orders_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapa.
        /// </summary>
        public static string Toolbar_Orders_Map {
            get {
                return ResourceManager.GetString("Toolbar_Orders_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string Toolbar_Orders_New {
            get {
                return ResourceManager.GetString("Toolbar_Orders_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planificador.
        /// </summary>
        public static string Toolbar_Orders_Planner {
            get {
                return ResourceManager.GetString("Toolbar_Orders_Planner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publicar.
        /// </summary>
        public static string Toolbar_Orders_Publish {
            get {
                return ResourceManager.GetString("Toolbar_Orders_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultas.
        /// </summary>
        public static string Toolbar_Orders_Queries {
            get {
                return ResourceManager.GetString("Toolbar_Orders_Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        public static string Toolbar_Products_Group {
            get {
                return ResourceManager.GetString("Toolbar_Products_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        public static string Toolbar_Products_List {
            get {
                return ResourceManager.GetString("Toolbar_Products_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo producto.
        /// </summary>
        public static string Toolbar_Products_New {
            get {
                return ResourceManager.GetString("Toolbar_Products_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sftp.
        /// </summary>
        public static string Toolbar_Sftp {
            get {
                return ResourceManager.GetString("Toolbar_Sftp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADMINISTRADOR.
        /// </summary>
        public static string Toolbar_Tab_Admin {
            get {
                return ResourceManager.GetString("Toolbar_Tab_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Toolbar_Tab_Home {
            get {
                return ResourceManager.GetString("Toolbar_Tab_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar.
        /// </summary>
        public static string Toolbar_Tab_Insert {
            get {
                return ResourceManager.GetString("Toolbar_Tab_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string Toolbar_Tab_Users {
            get {
                return ResourceManager.GetString("Toolbar_Tab_Users", resourceCulture);
            }
        }
    }
}
